import = [
  "~/.config/alacritty/themes/themes/catppuccin.toml"
  # "~/.config/alacritty/themes/themes/thelovelace.toml"
  # "~/.config/alacritty/themes/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.95
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 13
