"$schema" = 'https://starship.rs/config-schema.json'

[directory]
truncation_length = 8
truncation_symbol = '…/'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[container]
format = '[$symbol \[$name\]]($style) '

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []
